### ISSUE TITLE
Practica diseño de objetos 3D en Blender

### ISSUE THREAD

**Issue by Nancy2050** [SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-nancy-brenda-belem#2]
[Practica 2_Diseño de objetos en 3D.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-objeto-3d-en-blender-equipo-nancy-brenda-belem/files/8243272/Practica.2_Diseno.de.objetos.en.3D.pdf)

**Comment by Anthony4523** [comment]
Calificación: 20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado
